Name:           ros-indigo-fetch-simulation
Version:        0.7.3
Release:        0%{?dist}
Summary:        ROS fetch_simulation package

Group:          Development/Libraries
License:        BSD
URL:            https://docs.fetchrobotics.com/gazebo.html
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-fetch-gazebo
Requires:       ros-indigo-fetch-gazebo-demo
Requires:       ros-indigo-fetchit-challenge
BuildRequires:  ros-indigo-catkin

%description
Fetch Simulation, packages for working with Fetch and Freight in Gazebo

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Mar 28 2019 Alex Moriarty <amoriarty@fetchrobotics.com> - 0.7.3-0
- Autogenerated by Bloom

* Tue Mar 26 2019 Alex Moriarty <amoriarty@fetchrobotics.com> - 0.7.2-0
- Autogenerated by Bloom

