Name:           ros-melodic-fetch-gazebo
Version:        0.9.2
Release:        1%{?dist}
Summary:        ROS fetch_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/fetch_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       gazebo
Requires:       ros-melodic-actionlib
Requires:       ros-melodic-control-msgs
Requires:       ros-melodic-control-toolbox
Requires:       ros-melodic-depth-image-proc
Requires:       ros-melodic-fetch-description
Requires:       ros-melodic-gazebo-plugins
Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-image-proc
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-rgbd-launch
Requires:       ros-melodic-robot-controllers
Requires:       ros-melodic-robot-controllers-interface
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-xacro
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  ros-melodic-angles
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-control-toolbox
BuildRequires:  ros-melodic-gazebo-dev
BuildRequires:  ros-melodic-gazebo-plugins
BuildRequires:  ros-melodic-gazebo-ros
BuildRequires:  ros-melodic-robot-controllers
BuildRequires:  ros-melodic-robot-controllers-interface
BuildRequires:  ros-melodic-sensor-msgs

%description
Gazebo package for Fetch.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Aug 06 2019 Alex Moriarty <amoriarty@fetchrobotics.com> - 0.9.2-1
- Autogenerated by Bloom

* Thu Apr 04 2019 Alex Moriarty <amoriarty@fetchrobotics.com> - 0.9.1-0
- Autogenerated by Bloom

