Name:           ros-melodic-fetchit-challenge
Version:        0.9.1
Release:        0%{?dist}
Summary:        ROS fetchit_challenge package

Group:          Development/Libraries
License:        BSD
URL:            https://opensource.fetchrobotics.com/competition
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-controller-manager
Requires:       ros-melodic-effort-controllers
Requires:       ros-melodic-fetch-gazebo
Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-rospy
BuildRequires:  ros-melodic-catkin

%description
The fetchit_challenge package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Apr 04 2019 RDaneelOlivaw <duckfrost@theconstructsim.com> - 0.9.1-0
- Autogenerated by Bloom

