Name:           ros-jade-fetch-gazebo
Version:        0.8.0
Release:        0%{?dist}
Summary:        ROS fetch_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/fetch_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo
Requires:       ros-jade-actionlib
Requires:       ros-jade-control-toolbox
Requires:       ros-jade-depth-image-proc
Requires:       ros-jade-fetch-description
Requires:       ros-jade-gazebo-plugins
Requires:       ros-jade-gazebo-ros
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-image-proc
Requires:       ros-jade-nodelet
Requires:       ros-jade-rgbd-launch
Requires:       ros-jade-robot-controllers
Requires:       ros-jade-robot-controllers-interface
Requires:       ros-jade-trajectory-msgs
Requires:       ros-jade-xacro
BuildRequires:  gazebo-devel
BuildRequires:  ros-jade-angles
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-control-toolbox
BuildRequires:  ros-jade-gazebo-ros
BuildRequires:  ros-jade-robot-controllers
BuildRequires:  ros-jade-robot-controllers-interface

%description
Gazebo package for Fetch.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Dec 27 2016 Michael Ferguson <mferguson@fetchrobotics.com> - 0.8.0-0
- Autogenerated by Bloom

